"""Memory provenance constants.

Provenance answers "where did this memory come from" as a first-class column,
replacing category-based guessing in defense rules:

- PROFILE_SEED  : seeded at agent provisioning from the character profile.
                  Persona ground truth — write-time reconciliation must never
                  mutate these rows (contradictions go through spec §4).
- KNOWLEDGE_SEED: appended by an admin knowledge document to a TEMPLATE agent
                  (公司/产品/活动 facts) and published verbatim to its clones.
                  Admin-controlled ground truth — like profile_seed, chat-time
                  reconciliation must never mutate these rows, and the sync
                  pipeline identifies its own subset by this value.
- USER_STATED   : extracted from what the user actually said (chat pipeline
                  user side, contradiction resolutions).
- AI_AUTHORED   : extracted from the AI's own generated replies (chat pipeline
                  ai side). Never allowed to mint persona facts (偏好/身份).
- DAILY_SUMMARY : generated by the AI daily-life summary cron. Low-value
                  episodic trivia — first in line for consolidation.
- CONSOLIDATED  : produced by the L3 cluster compression job from archived
                  originals.
- REFLECTED     : 历史值, 不再产生新行。2026-07 试过把互动行为观察 (活跃时段 /
                  情绪构成 / 互动节奏) 写成独立记忆条目, 实测行不通: 72 条真实
                  消息里只有 7% 能召回它们, 且召回时多是误配 —— 这类内容是**特质**
                  不是事实, 而向量检索按话题相似度建索引, "他习惯用短句"不关于任何
                  话题。现在这些观察改为直接喂给用户画像 (每轮必然注入, 不需要被
                  检索到), 见 portrait._behaviour_section。
                  常量保留是因为生产上还有当时写入、随后归档的行引用这个值。

NULL = legacy rows written before the column existed (backfill script:
scripts/backfill_memory_provenance.py).
"""

from __future__ import annotations

PROFILE_SEED = "profile_seed"
KNOWLEDGE_SEED = "knowledge_seed"
USER_STATED = "user_stated"
AI_AUTHORED = "ai_authored"
DAILY_SUMMARY = "daily_summary"
CONSOLIDATED = "consolidated"
REFLECTED = "reflected"

VALID_PROVENANCES = frozenset({
    PROFILE_SEED, KNOWLEDGE_SEED, USER_STATED, AI_AUTHORED, DAILY_SUMMARY,
    CONSOLIDATED, REFLECTED,
})

# 有损压缩不该套在这些上面。CONSOLIDATED 本身就是压缩产物 (再压一次是复合损失);
# REFLECTED 已不再产生新行, 留在这里是让存量的归档行即使被恢复也不会被压。
COMPRESSION_EXEMPT = frozenset({CONSOLIDATED, REFLECTED})


def normalize_provenance(value: str | None) -> str | None:
    """Return the value if it is a known provenance, else None (stored as NULL)."""
    if value in VALID_PROVENANCES:
        return value
    return None
