"""Memory provenance constants.

Provenance answers "where did this memory come from" as a first-class column,
replacing category-based guessing in defense rules:

- PROFILE_SEED  : seeded at agent provisioning from the character profile.
                  Persona ground truth — write-time reconciliation must never
                  mutate these rows (contradictions go through spec §4).
- KNOWLEDGE_SEED: appended by an admin knowledge document to a TEMPLATE agent
                  (公司/产品/活动 facts) and published verbatim to its clones.
                  Admin-controlled ground truth — like profile_seed, chat-time
                  reconciliation must never mutate these rows, and the sync
                  pipeline identifies its own subset by this value.
- USER_STATED   : extracted from what the user actually said (chat pipeline
                  user side, contradiction resolutions).
- AI_AUTHORED   : extracted from the AI's own generated replies (chat pipeline
                  ai side). Never allowed to mint persona facts (偏好/身份).
- DAILY_SUMMARY : generated by the AI daily-life summary cron. Low-value
                  episodic trivia — first in line for consolidation.
- CONSOLIDATED  : produced by the L3 cluster compression job from archived
                  originals.
- REFLECTED     : derived by the weekly reflection job from verified behavioural
                  facts (活跃时段 / 情绪构成 / 互动节奏). Unlike every other
                  provenance these are **inferences, not statements** — nobody
                  ever said them. That is why they land at L2 rather than L1
                  (a wrong inference in the never-decay tier is permanent) and
                  why they are excluded from lossy compression.

NULL = legacy rows written before the column existed (backfill script:
scripts/backfill_memory_provenance.py).
"""

from __future__ import annotations

PROFILE_SEED = "profile_seed"
KNOWLEDGE_SEED = "knowledge_seed"
USER_STATED = "user_stated"
AI_AUTHORED = "ai_authored"
DAILY_SUMMARY = "daily_summary"
CONSOLIDATED = "consolidated"
REFLECTED = "reflected"

VALID_PROVENANCES = frozenset({
    PROFILE_SEED, KNOWLEDGE_SEED, USER_STATED, AI_AUTHORED, DAILY_SUMMARY,
    CONSOLIDATED, REFLECTED,
})

# 有损压缩不该套在这些上面。CONSOLIDATED 本身就是压缩产物 (再压一次是复合损失),
# REFLECTED 是推断 (压缩会把它的证据边界抹掉, 而没有证据的推断无法复核)。
COMPRESSION_EXEMPT = frozenset({CONSOLIDATED, REFLECTED})


def normalize_provenance(value: str | None) -> str | None:
    """Return the value if it is a known provenance, else None (stored as NULL)."""
    if value in VALID_PROVENANCES:
        return value
    return None
