"""系统提示词模板。"""

from app.services.prompt_defaults import (
    CONSISTENCY_RULES_PROMPT as CONSISTENCY_RULES,
    EMOTION_INSTRUCTION_PROMPT as EMOTION_INSTRUCTION,
    MEMORY_INSTRUCTION_PROMPT as MEMORY_INSTRUCTION,
    PERSONALITY_RULES_PROMPT as PERSONALITY_RULES,
    RESPONSE_INSTRUCTION_PROMPT as RESPONSE_INSTRUCTION,
    SYSTEM_BASE_PROMPT as SYSTEM_BASE,
)

# 回复约束 (PRD §3.2.1/§3.2.2)
MAX_PER_REPLY = 60           # 单条回复最大字数
MAX_REPLY_COUNT = 3          # 正常最大条数
EXPAND_MAX_REPLY_COUNT = 5   # 特殊放宽最大条数
MAX_TOTAL_CHARS = 150        # 正常总字数上限
EXPAND_MAX_TOTAL_CHARS = 200 # 特殊放宽总字数上限

# Token预算常量
MEMORY_TOKEN_BUDGET = 800
SUMMARIZER_TOKEN_BUDGET = 600
GRAPH_CONTEXT_TOKEN_BUDGET = 200
MAX_SYSTEM_PROMPT_TOKENS = 2000
MAX_RECENT_MESSAGES = 6
