"""系统提示词模板。"""

from app.services.prompting.defaults import (
    CONSISTENCY_RULES_PROMPT as CONSISTENCY_RULES,
    EMOTION_INSTRUCTION_PROMPT as EMOTION_INSTRUCTION,
    MEMORY_INSTRUCTION_PROMPT as MEMORY_INSTRUCTION,
    PERSONALITY_RULES_PROMPT as PERSONALITY_RULES,
    RESPONSE_INSTRUCTION_PROMPT as RESPONSE_INSTRUCTION,
    SYSTEM_BASE_PROMPT as SYSTEM_BASE,
)

# 回复约束 (spec §5.5: n = random.randint(1, 3) 均匀分布)
MAX_PER_REPLY = 60           # 单条回复最大字数
MAX_REPLY_COUNT = 3          # spec §5.5: 严格 1-3 均匀随机
MAX_TOTAL_CHARS = 150        # 总字数上限

# Token预算常量
MEMORY_TOKEN_BUDGET = 800
SUMMARIZER_TOKEN_BUDGET = 600
GRAPH_CONTEXT_TOKEN_BUDGET = 200
MAX_SYSTEM_PROMPT_TOKENS = 2000
CHAT_HISTORY_TOKEN_BUDGET = 4000  # 聊天记录 token 预算，从最新消息往前填充
