"""Prompt registry for admin management and runtime lookup."""

from __future__ import annotations

from dataclasses import dataclass

from app.services.prompting.defaults import (
    AI_PAD_PROMPT,
    AI_REPLY_EMOTION_PROMPT,
    APOLOGY_PROMPT,
    APOLOGY_REPLY_PROMPT,
    ATTACK_LEVEL_PROMPT,
    ATTACK_TARGET_PROMPT,
    BANNED_WORD_PROMPT,
    BLACKLIST_REPLY_PROMPT,
    BOUNDARY_FINAL_WARNING_PROMPT,
    CHARACTER_TEMPLATE_HEADER_PROMPT,
    CHARACTER_TEMPLATE_REQUIREMENTS_PROMPT,
    CONSISTENCY_RULES_PROMPT,
    CURRENT_STATE_REPLY_PROMPT,
    DAILY_SCHEDULE_PROMPT,
    DELAY_EXPLANATION_PROMPT,
    DELETION_CONFIRM_PROMPT,
    DELETION_INTENT_PROMPT,
    DELETION_REPLY_PROMPT,
    EMOTION_EXTRACTION_PROMPT,
    EMOTION_INSTRUCTION_PROMPT,
    END_REPLY_PROMPT,
    PERSONALITY_SCORING_PROMPT,
    INTENT_SPLIT_PROMPT,
    INTENT_UNIFIED_PROMPT,
    L3_MEMORY_REPLY_PROMPT,
    L3_TRIGGER_PROMPT,
    LIFE_OVERVIEW_PROMPT,
    LIFE_STORY_MAIN_GAP_FILL_PROMPT,
    LIGHT_ATTACK_REPLY_PROMPT,
    LOW_PATIENCE_REPLY_PROMPT,
    MEDIUM_ATTACK_REPLY_PROMPT,
    MEDIUM_MEMORY_REPLY_PROMPT,
    MEDIUM_PATIENCE_REPLY_PROMPT,
    MEMORY_CONTRADICTION_ANALYSIS_PROMPT,
    MEMORY_CONTRADICTION_DETECTION_PROMPT,
    MEMORY_CONTRADICTION_INQUIRY_PROMPT,
    MEMORY_CONTRADICTION_REPLY_PROMPT,
    MEMORY_EXTRACTION_AI_PROMPT,
    MEMORY_EXTRACTION_USER_PROMPT,
    MEMORY_INSTRUCTION_PROMPT,
    MEMORY_RELEVANCE_PROMPT,
    PERSONALITY_RULES_PROMPT,
    PORTRAIT_GENERATION_PROMPT,
    PORTRAIT_UPDATE_PROMPT,
    PROACTIVE_SILENCE_PLAIN_PROMPT,
    PROACTIVE_SILENCE_AI_MEMORY_PROMPT,
    PROACTIVE_SILENCE_USER_MEMORY_PROMPT,
    PROACTIVE_SILENCE_SCHEDULE_PROMPT,
    PROACTIVE_MEMORY_AI_PROMPT,
    PROACTIVE_MEMORY_USER_PROMPT,
    PROACTIVE_SCHEDULED_SCENE_PROMPT,
    PROACTIVE_DECAY_FINAL_PROMPT,
    PROACTIVE_FIRST_GREETING_PROMPT,
    PROACTIVE_SPECIAL_HOLIDAY_PROMPT,
    PROACTIVE_SPECIAL_BIRTHDAY_PROMPT,
    PROACTIVE_SPECIAL_REMINDER_PROMPT,
    PROACTIVE_SPECIAL_COMBINED_PROMPT,
    REPLY_SPLIT_2_PROMPT,
    REPLY_SPLIT_3_PROMPT,
    RESPONSE_INSTRUCTION_PROMPT,
    DAILY_SCHEDULE_WITH_USER_MEMORY_PROMPT,
    MEMORY_JUDGEMENT_AI_PROMPT,
    MEMORY_JUDGEMENT_USER_PROMPT,
    SCHEDULE_ADJUST_REPLY_PROMPT,
    SCHEDULE_DAILY_SUMMARY_MEMORIES_PROMPT,
    SCHEDULE_DAILY_SUMMARY_PROMPT,
    SCHEDULE_QUERY_REPLY_PROMPT,
    SEVERE_ATTACK_REPLY_PROMPT,
    STRONG_MEMORY_REPLY_PROMPT,
    SYSTEM_BASE_PROMPT,
    WEAK_MEMORY_REPLY_PROMPT,
)


@dataclass(frozen=True)
class PromptDefinition:
    key: str
    title: str
    stage: str
    category: str
    description: str
    default_text: str


PROMPT_DEFINITIONS = [
    PromptDefinition("chat.system_base", "聊天核心规则", "聊天热路径", "聊天", "系统人格锚点。", SYSTEM_BASE_PROMPT),
    PromptDefinition("chat.response_instruction", "聊天回复规则", "聊天热路径", "聊天", "条数、字数、语气与回复方式。", RESPONSE_INSTRUCTION_PROMPT),
    PromptDefinition("chat.personality_rules", "人格一致性规则", "聊天热路径", "聊天", "约束人格和表达风格。", PERSONALITY_RULES_PROMPT),
    PromptDefinition("chat.consistency_rules", "对话一致性规则", "聊天热路径", "聊天", "防止重复提问和自相矛盾。", CONSISTENCY_RULES_PROMPT),
    PromptDefinition("chat.emotion_instruction", "情绪注入规则", "聊天热路径", "聊天", "控制情绪如何影响语气。", EMOTION_INSTRUCTION_PROMPT),
    PromptDefinition("chat.memory_instruction", "记忆注入规则", "聊天热路径", "聊天", "控制记忆上下文提示语。", MEMORY_INSTRUCTION_PROMPT),
    PromptDefinition("memory.judgement_user", "记忆判断(用户)", "异步记忆", "记忆", "Spec §2.1.2：小模型二分类判断用户消息是否值得记忆（记/不记）。", MEMORY_JUDGEMENT_USER_PROMPT),
    PromptDefinition("memory.judgement_ai", "AI 信息记忆判断", "异步记忆", "记忆", "Spec §2.2.2：小模型二分类判断 AI 消息是否值得进入自我记忆（记/不记）。", MEMORY_JUDGEMENT_AI_PROMPT),
    PromptDefinition("memory.extraction_user", "用户长期记忆提取", "异步记忆", "记忆", "Spec §2.1.3：拆分+分类+打分合并一步，仅抽取用户侧记忆，存入 B 库 (memories_user)。", MEMORY_EXTRACTION_USER_PROMPT),
    PromptDefinition("memory.extraction_ai", "AI 自我长期记忆提取", "异步记忆", "记忆", "Spec §2.2.3：拆分+分类+打分合并一步，仅抽取 AI 自我记忆，存入 A 库 (memories_ai)。", MEMORY_EXTRACTION_AI_PROMPT),
    PromptDefinition("memory.contradiction_detection", "矛盾检测(交互)", "交互矛盾", "记忆", "Spec §4.1：用户消息 vs L1 核心记忆的热路径矛盾判断。", MEMORY_CONTRADICTION_DETECTION_PROMPT),
    PromptDefinition("memory.contradiction_inquiry", "矛盾询问", "交互矛盾", "记忆", "Spec §4.2：友好追问用户确认矛盾原因。", MEMORY_CONTRADICTION_INQUIRY_PROMPT),
    PromptDefinition("memory.contradiction_analysis", "矛盾判断(回复分析)", "交互矛盾", "记忆", "Spec §4.3：分析用户对矛盾询问的回答，输出 变化/新增/错误 + 调整方案。", MEMORY_CONTRADICTION_ANALYSIS_PROMPT),
    PromptDefinition("memory.contradiction_reply", "矛盾回复", "交互矛盾", "记忆", "Spec §4.5：用户解释后自然把话题拉回正轨。", MEMORY_CONTRADICTION_REPLY_PROMPT),
    PromptDefinition("memory.deletion_intent", "删除记忆意图识别", "异步记忆", "记忆", "Spec §5.1：小模型识别用户是否在要求删除记忆。", DELETION_INTENT_PROMPT),
    PromptDefinition("emotion.extraction", "用户 PAD 值判断", "异步情绪", "情绪", "Spec §3.3 + 指令模版 P26：用户消息 PAD 三维值。", EMOTION_EXTRACTION_PROMPT),
    PromptDefinition("schedule.life_overview", "生活画像生成", "作息系统", "作息", "Spec §2.1 + 指令模版 P20：200 字纯文本生活画像，7 个中文性格维度。", LIFE_OVERVIEW_PROMPT),
    PromptDefinition("schedule.daily_schedule", "每日作息生成", "作息系统", "作息", "Spec §2.1：70% 概率使用，生成当天作息（空闲/忙碌/很忙碌/睡眠 4 状态）。", DAILY_SCHEDULE_PROMPT),
    PromptDefinition("schedule.daily_schedule_with_memory", "每日作息生成(带用户记忆)", "作息系统", "作息", "Spec §2.1：30% 概率使用，作息中包含一项与用户记忆有关的事。", DAILY_SCHEDULE_WITH_USER_MEMORY_PROMPT),
    PromptDefinition("schedule.daily_summary", "昨日生活总结(文本)", "作息系统", "作息", "Spec §2.2：昨日作息+调整+主动日志 → 200 字第一人称总结文本。", SCHEDULE_DAILY_SUMMARY_PROMPT),
    PromptDefinition("schedule.daily_summary_memories", "昨日总结拆分打分", "作息系统", "记忆", "Spec §2.3：把总结文本拆分为记忆条目 + 五类分类 + 0-100 打分。", SCHEDULE_DAILY_SUMMARY_MEMORIES_PROMPT),
    PromptDefinition("portrait.generation", "用户画像生成", "异步画像", "画像", "Spec §1.6 + 指令模版 P23：200 字五段式用户画像。", PORTRAIT_GENERATION_PROMPT),
    PromptDefinition("portrait.update", "用户画像更新", "异步画像", "画像", "Spec §1.6 + 指令模版 P23：根据记忆变化增量更新画像。", PORTRAIT_UPDATE_PROMPT),
    PromptDefinition("proactive.silence_plain", "沉默唤醒(无记忆)", "主动交流", "主动消息", "沉默唤醒打招呼——不涉及记忆。", PROACTIVE_SILENCE_PLAIN_PROMPT),
    PromptDefinition("proactive.silence_ai_memory", "沉默唤醒(AI记忆)", "主动交流", "主动消息", "沉默唤醒——基于AI自身记忆轻带一句。", PROACTIVE_SILENCE_AI_MEMORY_PROMPT),
    PromptDefinition("proactive.silence_user_memory", "沉默唤醒(用户记忆)", "主动交流", "主动消息", "沉默唤醒——基于用户记忆轻带一句。", PROACTIVE_SILENCE_USER_MEMORY_PROMPT),
    PromptDefinition("proactive.silence_schedule", "沉默唤醒(作息)", "主动交流", "主动消息", "沉默唤醒——基于AI当前作息带一句。", PROACTIVE_SILENCE_SCHEDULE_PROMPT),
    PromptDefinition("proactive.memory_ai", "记忆主动(AI记忆)", "主动交流", "主动消息", "记忆主动——有感而发自己的经历。", PROACTIVE_MEMORY_AI_PROMPT),
    PromptDefinition("proactive.memory_user", "记忆主动(用户记忆)", "主动交流", "主动消息", "记忆主动——忽然想起用户的事。", PROACTIVE_MEMORY_USER_PROMPT),
    PromptDefinition("proactive.scheduled_scene", "定时情景(AI作息)", "主动交流", "主动消息", "基于AI当前作息状态分享一句。", PROACTIVE_SCHEDULED_SCENE_PROMPT),
    PromptDefinition("proactive.decay_final", "衰减最后一次回复", "主动交流", "主动消息", "三级衰减终止前的温和告别。", PROACTIVE_DECAY_FINAL_PROMPT),
    PromptDefinition("proactive.first_greeting", "AI首次打招呼", "主动交流", "主动消息", "用户首次进入聊天时AI的开场白。", PROACTIVE_FIRST_GREETING_PROMPT),
    PromptDefinition("proactive.special_holiday", "特殊日期(节日)", "主动交流", "主动消息", "春节/元旦主动祝福。", PROACTIVE_SPECIAL_HOLIDAY_PROMPT),
    PromptDefinition("proactive.special_birthday", "特殊日期(生日)", "主动交流", "主动消息", "用户生日主动祝福。", PROACTIVE_SPECIAL_BIRTHDAY_PROMPT),
    PromptDefinition("proactive.special_reminder", "特殊日期(提醒)", "主动交流", "主动消息", "用户提醒日期主动提醒。", PROACTIVE_SPECIAL_REMINDER_PROMPT),
    PromptDefinition("proactive.special_combined", "特殊日期(合并)", "主动交流", "主动消息", "同日多个特殊日期合并消息。", PROACTIVE_SPECIAL_COMBINED_PROMPT),
    PromptDefinition("boundary.apology", "道歉真诚度检测", "边界系统", "边界", "【工程扩展】拉黑态防 spam-unblock：用 sincerity 阈值闸门用户是否真心道歉，spec §2.6.2.1 的 intent.unified 仅做意图分类不评估真诚度。", APOLOGY_PROMPT),
    PromptDefinition("agent.personality_scoring", "AI 性格打分", "初始化", "初始化", "Spec §1.3 + 指令模版 P26：agent 创建时用 LLM 把用户选的 7 维性格推导为 MBTI 8 维分数。在后台异步任务中调用，不阻塞 API 响应。", PERSONALITY_SCORING_PROMPT),
    PromptDefinition("character.template_header", "背景模板·开头规则", "初始化", "初始化", "Spec §1.4「AI背景生成」核心生成规则段。同时是 admin「Agent管理 / 背景模板 / 生成规则」的系统默认值，新建模板 / 重置默认按钮读此值。Per-template 可在背景模板页覆盖。", CHARACTER_TEMPLATE_HEADER_PROMPT),
    PromptDefinition("character.template_requirements", "背景模板·输出要求", "初始化", "初始化", "Spec §1.4「AI背景生成」输出格式 / 字段填充规则段。同时是 admin「Agent管理 / 背景模板 / 输出要求」的系统默认值。Per-template 可在背景模板页覆盖。{index} 占位符在运行时被替换为角色序号。", CHARACTER_TEMPLATE_REQUIREMENTS_PROMPT),
    PromptDefinition("life_story.main_gap_fill", "L1 记忆缺口补齐", "初始化", "初始化", "【工程附加 / 技术债】spec §1.4「AI背景生成」原本是单步生成全部 L1 记忆，但代码拆成两步：(1) admin「背景模板」批量预生成 character_profiles JSON，(2) 用户创建 agent 时 convert_profile_to_memories 把 profile 字段映射成记忆条目，发现某大类条数不足 → 此 prompt LLM 补齐。如要回归 spec 单步流程需消除此 prompt + 重写 character.py + life_story.py。", LIFE_STORY_MAIN_GAP_FILL_PROMPT),

    # ── spec §2-§6 新增（4.19 指令模板） ──
    PromptDefinition("boundary.attack_target", "攻击目标识别", "边界系统", "边界", "判断攻击目标类型（攻击AI/第三方/无负面/无目标脏话）。", ATTACK_TARGET_PROMPT),
    PromptDefinition("boundary.attack_level", "攻击级别识别", "边界系统", "边界", "判断攻击级别 K1/K2/K3。", ATTACK_LEVEL_PROMPT),
    PromptDefinition("boundary.banned_word", "违禁词判断", "边界系统", "边界", "判断消息是否含违禁内容（谐音/缩写/涉黄涉暴等）。", BANNED_WORD_PROMPT),
    PromptDefinition("boundary.light_attack_reply", "轻度攻击回复(K1)", "边界系统", "边界", "K1 级别的生气回复。", LIGHT_ATTACK_REPLY_PROMPT),
    PromptDefinition("boundary.medium_attack_reply", "中度攻击回复(K2)", "边界系统", "边界", "K2 级别的认真回复。", MEDIUM_ATTACK_REPLY_PROMPT),
    PromptDefinition("boundary.severe_attack_reply", "重度攻击回复(K3)", "边界系统", "边界", "K3 级别的坚定底线回复。", SEVERE_ATTACK_REPLY_PROMPT),
    PromptDefinition("boundary.medium_patience_reply", "中耐心回复", "边界系统", "边界", "中耐心区间的正常对话，自然带出情绪。", MEDIUM_PATIENCE_REPLY_PROMPT),
    PromptDefinition("boundary.low_patience_reply", "低耐心回复", "边界系统", "边界", "低耐心区间的简短冷淡回复。", LOW_PATIENCE_REPLY_PROMPT),
    PromptDefinition("boundary.final_warning", "最终警告", "边界系统", "边界", "指令模版【最终警告】：PM 补丁规则—攻击 AI 扣分后 patience<20 时覆写 K1/K2/K3。规则 spec §2.6 步骤 5.4 未列此档。", BOUNDARY_FINAL_WARNING_PROMPT),
    PromptDefinition("boundary.blacklist_reply", "拉黑回复", "边界系统", "边界", "没耐心(≤0)的拉黑固定回复。", BLACKLIST_REPLY_PROMPT),
    PromptDefinition("boundary.apology_reply", "道歉/承诺回复", "边界系统", "边界", "接受道歉或承诺时的和解回复。", APOLOGY_REPLY_PROMPT),
    PromptDefinition("intent.unified", "统一意图识别", "意图识别", "意图", "多选意图识别（8 类）。", INTENT_UNIFIED_PROMPT),
    PromptDefinition("intent.split", "用户意图拆分", "意图识别", "意图", "将多意图消息拆分为子意图片段。", INTENT_SPLIT_PROMPT),
    PromptDefinition("intent.end_reply", "终结意图回复", "意图处理", "意图", "用户想结束对话时的告别回复。", END_REPLY_PROMPT),
    PromptDefinition("intent.schedule_query_reply", "计划查询回复", "意图处理", "意图", "回答 AI 当前/未来日程。", SCHEDULE_QUERY_REPLY_PROMPT),
    PromptDefinition("intent.schedule_adjust_reply", "作息调整回复", "意图处理", "意图", "同意用户调整作息并输出 adjustment。", SCHEDULE_ADJUST_REPLY_PROMPT),
    PromptDefinition("intent.current_state_reply", "当前状态回复", "意图处理", "意图", "回答 AI 现在在做什么。", CURRENT_STATE_REPLY_PROMPT),
    PromptDefinition("intent.deletion_confirm", "删除意图确认", "意图处理", "意图", "询问用户具体想删除的内容。", DELETION_CONFIRM_PROMPT),
    PromptDefinition("intent.deletion_reply", "删除回复", "意图处理", "意图", "表示已忘记并自然带过。", DELETION_REPLY_PROMPT),
    PromptDefinition("memory.relevance", "回忆相关度判断", "日常交流", "记忆", "判断消息与记忆的强/中/弱相关。", MEMORY_RELEVANCE_PROMPT),
    PromptDefinition("memory.l3_trigger", "L3 唤醒判断", "日常交流", "记忆", "是否需要调用 L3 久远记忆（不满纠正/请求更久/无）。", L3_TRIGGER_PROMPT),
    PromptDefinition("memory.weak_reply", "弱记忆回复", "日常交流", "记忆", "相关度弱时的自然回复。", WEAK_MEMORY_REPLY_PROMPT),
    PromptDefinition("memory.medium_reply", "中记忆回复", "日常交流", "记忆", "相关度中时的自然回复。", MEDIUM_MEMORY_REPLY_PROMPT),
    PromptDefinition("memory.strong_reply", "强记忆回复", "日常交流", "记忆", "相关度强时的自然回复。", STRONG_MEMORY_REPLY_PROMPT),
    PromptDefinition("memory.l3_reply", "久远记忆回复", "日常交流", "记忆", "L3 久远记忆的模糊回复。", L3_MEMORY_REPLY_PROMPT),
    PromptDefinition("reply.delay_explanation", "延迟解释回复", "异步回复", "回复加工", "延迟≥1分钟时的独立解释消息。", DELAY_EXPLANATION_PROMPT),
    PromptDefinition("reply.emotion_detection", "AI 语句情绪识别", "回复加工", "回复加工", "识别 AI 回复的情绪标签和强度。", AI_REPLY_EMOTION_PROMPT),
    PromptDefinition("reply.split_2", "AI 语句拆分(2句)", "回复加工", "回复加工", "将回复拆分为 2 条自然语句。", REPLY_SPLIT_2_PROMPT),
    PromptDefinition("reply.split_3", "AI 语句拆分(3句)", "回复加工", "回复加工", "将回复拆分为 3 条自然语句。", REPLY_SPLIT_3_PROMPT),
    PromptDefinition("emotion.ai_pad", "AI PAD 值判断", "前置情感", "情绪", "从 AI 当前作息+上下文推测 AI PAD。", AI_PAD_PROMPT),
]

PROMPT_DEFINITION_MAP = {definition.key: definition for definition in PROMPT_DEFINITIONS}
