"""Prompt registry for admin management and runtime lookup."""

from __future__ import annotations

from dataclasses import dataclass

from app.services.prompting.defaults import (
    AI_PAD_PROMPT,
    AI_REPLY_EMOTION_PROMPT,
    APOLOGY_PROMPT,
    APOLOGY_REPLY_PROMPT,
    ATTACK_INTENT_PROMPT,
    ATTACK_LEVEL_PROMPT,
    ATTACK_TARGET_PROMPT,
    BANNED_WORD_PROMPT,
    BLACKLIST_REPLY_PROMPT,
    COMPRESS_PROMPT,
    CONFLICT_DETECTION_PROMPT,
    CONSISTENCY_RULES_PROMPT,
    CONSOLIDATE_SUMMARIZE_PROMPT,
    CURRENT_STATE_REPLY_PROMPT,
    DAILY_SCHEDULE_PROMPT,
    DELAY_EXPLANATION_PROMPT,
    DELETION_CONFIRM_PROMPT,
    DELETION_INTENT_PROMPT,
    DELETION_REPLY_PROMPT,
    EMOTION_BASELINE_PROMPT,
    EMOTION_EXTRACTION_PROMPT,
    EMOTION_INSTRUCTION_PROMPT,
    END_REPLY_PROMPT,
    FAST_FACT_PROMPT,
    IDENTITY_GENERATION_PROMPT,
    INITIAL_SELF_MEMORY_PROMPT,
    INTENT_SPLIT_PROMPT,
    INTENT_UNIFIED_PROMPT,
    L3_MEMORY_REPLY_PROMPT,
    L3_TRIGGER_PROMPT,
    LAYER1_REVIEW_PROMPT,
    LAYER2_DISTILLATION_PROMPT,
    LAYER3_STATE_PROMPT,
    LIFE_OVERVIEW_PROMPT,
    LIGHT_ATTACK_REPLY_PROMPT,
    LOW_PATIENCE_REPLY_PROMPT,
    MEDIUM_ATTACK_REPLY_PROMPT,
    MEDIUM_MEMORY_REPLY_PROMPT,
    MEDIUM_PATIENCE_REPLY_PROMPT,
    MEMORY_EXTRACTION_PROMPT,
    MEMORY_INSTRUCTION_PROMPT,
    MEMORY_RELEVANCE_PROMPT,
    MEMORY_SCORING_PROMPT,
    PERSONALITY_RULES_PROMPT,
    PORTRAIT_GENERATION_PROMPT,
    PORTRAIT_UPDATE_PROMPT,
    PROACTIVE_PROMPT,
    PROACTIVE_SILENCE_PLAIN_PROMPT,
    PROACTIVE_SILENCE_AI_MEMORY_PROMPT,
    PROACTIVE_SILENCE_USER_MEMORY_PROMPT,
    PROACTIVE_SILENCE_SCHEDULE_PROMPT,
    PROACTIVE_MEMORY_AI_PROMPT,
    PROACTIVE_MEMORY_USER_PROMPT,
    PROACTIVE_SCHEDULED_SCENE_PROMPT,
    PROACTIVE_DECAY_FINAL_PROMPT,
    PROACTIVE_FIRST_GREETING_PROMPT,
    PROACTIVE_SPECIAL_HOLIDAY_PROMPT,
    PROACTIVE_SPECIAL_BIRTHDAY_PROMPT,
    PROACTIVE_SPECIAL_REMINDER_PROMPT,
    PROACTIVE_SPECIAL_COMBINED_PROMPT,
    QUERY_ANALYZER_PROMPT,
    REPLY_SPLIT_2_PROMPT,
    REPLY_SPLIT_3_PROMPT,
    RESPONSE_INSTRUCTION_PROMPT,
    SCHEDULE_ADJUST_REPLY_PROMPT,
    SCHEDULE_QUERY_REPLY_PROMPT,
    SCHEDULE_REVIEW_PROMPT,
    SELF_MEMORY_PROMPT,
    SEVERE_ATTACK_REPLY_PROMPT,
    SEVERITY_PROMPT,
    STRONG_MEMORY_REPLY_PROMPT,
    SYSTEM_BASE_PROMPT,
    USER_PAD_PROMPT,
    WEAK_MEMORY_REPLY_PROMPT,
)


@dataclass(frozen=True)
class PromptDefinition:
    key: str
    title: str
    stage: str
    category: str
    description: str
    default_text: str


PROMPT_DEFINITIONS = [
    PromptDefinition("chat.system_base", "聊天核心规则", "聊天热路径", "聊天", "系统人格锚点。", SYSTEM_BASE_PROMPT),
    PromptDefinition("chat.response_instruction", "聊天回复规则", "聊天热路径", "聊天", "条数、字数、语气与回复方式。", RESPONSE_INSTRUCTION_PROMPT),
    PromptDefinition("chat.personality_rules", "人格一致性规则", "聊天热路径", "聊天", "约束人格和表达风格。", PERSONALITY_RULES_PROMPT),
    PromptDefinition("chat.consistency_rules", "对话一致性规则", "聊天热路径", "聊天", "防止重复提问和自相矛盾。", CONSISTENCY_RULES_PROMPT),
    PromptDefinition("chat.emotion_instruction", "情绪注入规则", "聊天热路径", "聊天", "控制情绪如何影响语气。", EMOTION_INSTRUCTION_PROMPT),
    PromptDefinition("chat.memory_instruction", "记忆注入规则", "聊天热路径", "聊天", "控制记忆上下文提示语。", MEMORY_INSTRUCTION_PROMPT),
    PromptDefinition("memory.fast_fact", "热路径事实提取", "聊天热路径", "记忆", "同步提取 working memory。", FAST_FACT_PROMPT),
    PromptDefinition("memory.extraction", "长期记忆提取", "异步记忆", "记忆", "对话后抽取 L1/L2/L3 记忆。", MEMORY_EXTRACTION_PROMPT),
    PromptDefinition("memory.scoring", "记忆相关性评分", "检索重排", "记忆", "LLM 辅助记忆相关性和重要性评分。", MEMORY_SCORING_PROMPT),
    PromptDefinition("memory.conflict_detection", "记忆冲突检测", "异步记忆", "记忆", "检测新旧核心记忆冲突。", CONFLICT_DETECTION_PROMPT),
    PromptDefinition("memory.deletion_intent", "删除记忆意图识别", "异步记忆", "记忆", "识别用户删除记忆请求。", DELETION_INTENT_PROMPT),
    PromptDefinition("memory.query_analyzer", "检索意图分析", "检索前置", "记忆", "判断检索类型与实体。", QUERY_ANALYZER_PROMPT),
    PromptDefinition("memory.compression", "记忆压缩总结", "定时压缩", "记忆", "多条记忆压缩为总结。", COMPRESS_PROMPT),
    PromptDefinition("memory.consolidation", "记忆整合总结", "定时整合", "记忆", "相似记忆整合为长期记忆。", CONSOLIDATE_SUMMARIZE_PROMPT),
    PromptDefinition("emotion.baseline", "情感基线计算", "初始化", "情绪", "小模型推导 PAD 情感基线。", EMOTION_BASELINE_PROMPT),
    PromptDefinition("emotion.extraction", "情绪提取", "异步情绪", "情绪", "用户消息 PAD 提取。", EMOTION_EXTRACTION_PROMPT),
    PromptDefinition("summarizer.layer1_review", "摘要层1-对话回顾", "异步摘要", "摘要", "30 条消息回顾总结。", LAYER1_REVIEW_PROMPT),
    PromptDefinition("summarizer.layer2_distillation", "摘要层2-记忆提炼", "异步摘要", "摘要", "记忆与当前消息提炼。", LAYER2_DISTILLATION_PROMPT),
    PromptDefinition("summarizer.layer3_state", "摘要层3-状态分析", "异步摘要", "摘要", "当前情绪/话题/意图分析。", LAYER3_STATE_PROMPT),
    PromptDefinition("schedule.life_overview", "生活画像生成", "作息系统", "作息", "生成 AI 长期生活画像。", LIFE_OVERVIEW_PROMPT),
    PromptDefinition("schedule.daily_schedule", "每日作息生成", "作息系统", "作息", "生成当天具体作息安排。", DAILY_SCHEDULE_PROMPT),
    PromptDefinition("schedule.review", "作息回顾总结", "作息系统", "作息", "把一天经历沉淀成 AI 自我记忆。", SCHEDULE_REVIEW_PROMPT),
    PromptDefinition("portrait.generation", "用户画像生成", "异步画像", "画像", "从记忆生成用户画像。", PORTRAIT_GENERATION_PROMPT),
    PromptDefinition("portrait.update", "用户画像更新", "异步画像", "画像", "根据变化增量更新画像。", PORTRAIT_UPDATE_PROMPT),
    PromptDefinition("proactive.message", "主动消息生成(legacy统一)", "主动交流", "主动消息", "生成 AI 主动发起的消息(兜底/遗留)。", PROACTIVE_PROMPT),
    PromptDefinition("proactive.silence_plain", "沉默唤醒(无记忆)", "主动交流", "主动消息", "沉默唤醒打招呼——不涉及记忆。", PROACTIVE_SILENCE_PLAIN_PROMPT),
    PromptDefinition("proactive.silence_ai_memory", "沉默唤醒(AI记忆)", "主动交流", "主动消息", "沉默唤醒——基于AI自身记忆轻带一句。", PROACTIVE_SILENCE_AI_MEMORY_PROMPT),
    PromptDefinition("proactive.silence_user_memory", "沉默唤醒(用户记忆)", "主动交流", "主动消息", "沉默唤醒——基于用户记忆轻带一句。", PROACTIVE_SILENCE_USER_MEMORY_PROMPT),
    PromptDefinition("proactive.silence_schedule", "沉默唤醒(作息)", "主动交流", "主动消息", "沉默唤醒——基于AI当前作息带一句。", PROACTIVE_SILENCE_SCHEDULE_PROMPT),
    PromptDefinition("proactive.memory_ai", "记忆主动(AI记忆)", "主动交流", "主动消息", "记忆主动——有感而发自己的经历。", PROACTIVE_MEMORY_AI_PROMPT),
    PromptDefinition("proactive.memory_user", "记忆主动(用户记忆)", "主动交流", "主动消息", "记忆主动——忽然想起用户的事。", PROACTIVE_MEMORY_USER_PROMPT),
    PromptDefinition("proactive.scheduled_scene", "定时情景(AI作息)", "主动交流", "主动消息", "基于AI当前作息状态分享一句。", PROACTIVE_SCHEDULED_SCENE_PROMPT),
    PromptDefinition("proactive.decay_final", "衰减最后一次回复", "主动交流", "主动消息", "三级衰减终止前的温和告别。", PROACTIVE_DECAY_FINAL_PROMPT),
    PromptDefinition("proactive.first_greeting", "AI首次打招呼", "主动交流", "主动消息", "用户首次进入聊天时AI的开场白。", PROACTIVE_FIRST_GREETING_PROMPT),
    PromptDefinition("proactive.special_holiday", "特殊日期(节日)", "主动交流", "主动消息", "春节/元旦主动祝福。", PROACTIVE_SPECIAL_HOLIDAY_PROMPT),
    PromptDefinition("proactive.special_birthday", "特殊日期(生日)", "主动交流", "主动消息", "用户生日主动祝福。", PROACTIVE_SPECIAL_BIRTHDAY_PROMPT),
    PromptDefinition("proactive.special_reminder", "特殊日期(提醒)", "主动交流", "主动消息", "用户提醒日期主动提醒。", PROACTIVE_SPECIAL_REMINDER_PROMPT),
    PromptDefinition("proactive.special_combined", "特殊日期(合并)", "主动交流", "主动消息", "同日多个特殊日期合并消息。", PROACTIVE_SPECIAL_COMBINED_PROMPT),
    PromptDefinition("boundary.attack_intent", "攻击意图识别", "边界系统", "边界", "判断攻击意图类别。", ATTACK_INTENT_PROMPT),
    PromptDefinition("boundary.severity", "攻击严重度评估", "边界系统", "边界", "评估攻击消息严重度。", SEVERITY_PROMPT),
    PromptDefinition("boundary.apology", "道歉识别", "边界系统", "边界", "识别是否为有效道歉。", APOLOGY_PROMPT),
    PromptDefinition("self_memory.daily", "AI 自我记忆生成", "AI 自我记忆", "自我记忆", "从每日对话生成 AI 视角记忆。", SELF_MEMORY_PROMPT),
    PromptDefinition("self_memory.initial", "AI 初始自我记忆", "AI 自我记忆", "自我记忆", "创建时生成 3-5 条核心自我认知。", INITIAL_SELF_MEMORY_PROMPT),
    PromptDefinition("agent.identity_generation", "AI 身份信息生成", "初始化", "初始化", "根据人格推导 age/occupation/city。", IDENTITY_GENERATION_PROMPT),

    # ── spec §2-§6 新增（4.19 指令模板） ──
    PromptDefinition("boundary.attack_target", "攻击目标识别", "边界系统", "边界", "判断攻击目标类型（攻击AI/第三方/无负面/无目标脏话）。", ATTACK_TARGET_PROMPT),
    PromptDefinition("boundary.attack_level", "攻击级别识别", "边界系统", "边界", "判断攻击级别 K1/K2/K3。", ATTACK_LEVEL_PROMPT),
    PromptDefinition("boundary.banned_word", "违禁词判断", "边界系统", "边界", "判断消息是否含违禁内容（谐音/缩写/涉黄涉暴等）。", BANNED_WORD_PROMPT),
    PromptDefinition("boundary.light_attack_reply", "轻度攻击回复(K1)", "边界系统", "边界", "K1 级别的生气回复。", LIGHT_ATTACK_REPLY_PROMPT),
    PromptDefinition("boundary.medium_attack_reply", "中度攻击回复(K2)", "边界系统", "边界", "K2 级别的认真回复。", MEDIUM_ATTACK_REPLY_PROMPT),
    PromptDefinition("boundary.severe_attack_reply", "重度攻击回复(K3)", "边界系统", "边界", "K3 级别的坚定底线回复。", SEVERE_ATTACK_REPLY_PROMPT),
    PromptDefinition("boundary.medium_patience_reply", "中耐心回复", "边界系统", "边界", "中耐心区间的正常对话，自然带出情绪。", MEDIUM_PATIENCE_REPLY_PROMPT),
    PromptDefinition("boundary.low_patience_reply", "低耐心回复", "边界系统", "边界", "低耐心区间的简短冷淡回复。", LOW_PATIENCE_REPLY_PROMPT),
    PromptDefinition("boundary.blacklist_reply", "拉黑回复", "边界系统", "边界", "没耐心(≤0)的拉黑固定回复。", BLACKLIST_REPLY_PROMPT),
    PromptDefinition("boundary.apology_reply", "道歉/承诺回复", "边界系统", "边界", "接受道歉或承诺时的和解回复。", APOLOGY_REPLY_PROMPT),
    PromptDefinition("intent.unified", "统一意图识别", "意图识别", "意图", "多选意图识别（8 类）。", INTENT_UNIFIED_PROMPT),
    PromptDefinition("intent.split", "用户意图拆分", "意图识别", "意图", "将多意图消息拆分为子意图片段。", INTENT_SPLIT_PROMPT),
    PromptDefinition("intent.end_reply", "终结意图回复", "意图处理", "意图", "用户想结束对话时的告别回复。", END_REPLY_PROMPT),
    PromptDefinition("intent.schedule_query_reply", "计划查询回复", "意图处理", "意图", "回答 AI 当前/未来日程。", SCHEDULE_QUERY_REPLY_PROMPT),
    PromptDefinition("intent.schedule_adjust_reply", "作息调整回复", "意图处理", "意图", "同意用户调整作息并输出 adjustment。", SCHEDULE_ADJUST_REPLY_PROMPT),
    PromptDefinition("intent.current_state_reply", "当前状态回复", "意图处理", "意图", "回答 AI 现在在做什么。", CURRENT_STATE_REPLY_PROMPT),
    PromptDefinition("intent.deletion_confirm", "删除意图确认", "意图处理", "意图", "询问用户具体想删除的内容。", DELETION_CONFIRM_PROMPT),
    PromptDefinition("intent.deletion_reply", "删除回复", "意图处理", "意图", "表示已忘记并自然带过。", DELETION_REPLY_PROMPT),
    PromptDefinition("memory.relevance", "回忆相关度判断", "日常交流", "记忆", "判断消息与记忆的强/中/弱相关。", MEMORY_RELEVANCE_PROMPT),
    PromptDefinition("memory.l3_trigger", "L3 唤醒判断", "日常交流", "记忆", "是否需要调用 L3 久远记忆（不满纠正/请求更久/无）。", L3_TRIGGER_PROMPT),
    PromptDefinition("memory.weak_reply", "弱记忆回复", "日常交流", "记忆", "相关度弱时的自然回复。", WEAK_MEMORY_REPLY_PROMPT),
    PromptDefinition("memory.medium_reply", "中记忆回复", "日常交流", "记忆", "相关度中时的自然回复。", MEDIUM_MEMORY_REPLY_PROMPT),
    PromptDefinition("memory.strong_reply", "强记忆回复", "日常交流", "记忆", "相关度强时的自然回复。", STRONG_MEMORY_REPLY_PROMPT),
    PromptDefinition("memory.l3_reply", "久远记忆回复", "日常交流", "记忆", "L3 久远记忆的模糊回复。", L3_MEMORY_REPLY_PROMPT),
    PromptDefinition("reply.delay_explanation", "延迟解释回复", "异步回复", "回复加工", "延迟≥1分钟时的独立解释消息。", DELAY_EXPLANATION_PROMPT),
    PromptDefinition("reply.emotion_detection", "AI 语句情绪识别", "回复加工", "回复加工", "识别 AI 回复的情绪标签和强度。", AI_REPLY_EMOTION_PROMPT),
    PromptDefinition("reply.split_2", "AI 语句拆分(2句)", "回复加工", "回复加工", "将回复拆分为 2 条自然语句。", REPLY_SPLIT_2_PROMPT),
    PromptDefinition("reply.split_3", "AI 语句拆分(3句)", "回复加工", "回复加工", "将回复拆分为 3 条自然语句。", REPLY_SPLIT_3_PROMPT),
    PromptDefinition("emotion.user_pad", "用户 PAD 值判断", "前置情感", "情绪", "从用户消息输出 PAD 三维值。", USER_PAD_PROMPT),
    PromptDefinition("emotion.ai_pad", "AI PAD 值判断", "前置情感", "情绪", "从 AI 当前作息+上下文推测 AI PAD。", AI_PAD_PROMPT),
]

PROMPT_DEFINITION_MAP = {definition.key: definition for definition in PROMPT_DEFINITIONS}
